"""first revision

Revision ID: 1c2866bff988
Revises: 
Create Date: 2019-10-11 11:29:57.836644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c2866bff988'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('project_code', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('project_category', sa.String(), nullable=True),
    sa.Column('project_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code')
    )
    op.create_index(op.f('ix_projects_created_date'), 'projects', ['created_date'], unique=False)
    op.create_table('costcodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('costcode', sa.String(), nullable=False),
    sa.Column('costcode_category', sa.String(), nullable=True),
    sa.Column('costcode_description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_costcodes_created_date'), 'costcodes', ['created_date'], unique=False)
    op.create_index(op.f('ix_costcodes_project_id'), 'costcodes', ['project_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('cost_code_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cost_code_id'], ['costcodes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_cost_code_id'), 'transactions', ['cost_code_id'], unique=False)
    op.create_index(op.f('ix_transactions_created_date'), 'transactions', ['created_date'], unique=False)
    op.create_index(op.f('ix_transactions_project_id'), 'transactions', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_project_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_cost_code_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_costcodes_project_id'), table_name='costcodes')
    op.drop_index(op.f('ix_costcodes_created_date'), table_name='costcodes')
    op.drop_table('costcodes')
    op.drop_index(op.f('ix_projects_created_date'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
