"""added default_costcodes

Revision ID: 3964655e42cf
Revises: 597207ca9591
Create Date: 2019-11-07 14:28:34.491845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3964655e42cf'
down_revision = '597207ca9591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_costcodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('costcode', sa.String(), nullable=False),
    sa.Column('costcode_category', sa.String(), nullable=True),
    sa.Column('costcode_description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_default_costcodes_created_date'), 'default_costcodes', ['created_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_default_costcodes_created_date'), table_name='default_costcodes')
    op.drop_table('default_costcodes')
    # ### end Alembic commands ###
