"""added default_costcodes

Revision ID: 597207ca9591
Revises: 06ab6dea9b4a
Create Date: 2019-11-07 14:26:02.592845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597207ca9591'
down_revision = '06ab6dea9b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
