"""removed boolean from projects

Revision ID: cf9d315827cc
Revises: 1c2866bff988
Create Date: 2019-10-11 11:31:37.326592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cf9d315827cc"
down_revision = "1c2866bff988"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # required for sqlite drop tables
    with op.batch_alter_table("projects") as batch_op:
        batch_op.drop_column("project_active")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("project_active", sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
